# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Version(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    audio_locale: str
    guid: str
    is_premium_only: bool
    media_guid: str
    original: bool
    roles: list[str]
    season_guid: str
    variant: str


class AdBreak(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    offset_ms: int
    type: str


class ThumbnailItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: int
    source: str
    type: str
    width: int


class Images(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    thumbnail: list[list[ThumbnailItem]]


class ExtendedMaturityRating(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: str
    rating: str
    system: str


class Datum(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    season_display_number: str
    slug_title: str
    maturity_ratings: list[str]
    channel_id: str
    audio_locale: str
    season_slug_title: str
    is_subbed: bool
    versions: list[Version]
    availability_starts: AwareDatetime
    content_descriptors: list[str]
    description: str
    availability_status: str
    seo_title: str
    premium_available_date: AwareDatetime
    eligible_region: str
    identifier: str
    roles: list[str]
    next_episode_title: str
    ad_breaks: list[AdBreak]
    streams_link: str
    series_id: str
    episode: str
    episode_air_date: AwareDatetime
    availability_ends: AwareDatetime
    free_available_date: AwareDatetime
    slug: str
    mature_blocked: bool
    is_clip: bool
    premium_date: None
    next_episode_id: str
    media_type: str
    production_episode_id: str
    closed_captions_available: bool
    sequence_number: int
    images: Images
    listing_id: str
    season_title: str
    season_id: str
    episode_number: int
    id: str
    season_tags: list[str]
    available_offline: bool
    series_title: str
    seo_description: str
    availability_notes: str
    extended_maturity_rating: ExtendedMaturityRating
    recent_audio_locale: str
    season_number: int
    title: str
    is_premium_only: bool
    duration_ms: int
    is_mature: bool
    series_slug_title: str
    season_sequence_number: int
    recent_variant: str
    hd_flag: bool
    available_date: None
    subtitle_locales: list[str]
    is_dubbed: bool
    upload_date: AwareDatetime


class Meta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    versions_considered: bool


class Episodes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: int
    data: list[Datum]
    meta: Meta
