# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Version(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    audio_locale: str
    guid: str
    is_premium_only: bool
    media_guid: str
    original: bool
    roles: list[str]
    season_guid: str
    variant: str


class ExtendedMaturityRating(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    level: str
    rating: str
    system: str


class ThumbnailItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    height: int
    source: str
    type: str
    width: int


class Images(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    thumbnail: list[list[ThumbnailItem]]


class AdBreak(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    offset_ms: int
    type: str


class Datum(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    is_dubbed: bool
    available_date: None
    title: str
    series_title: str
    availability_ends: AwareDatetime
    media_type: str
    versions: list[Version] | None = None
    mature_blocked: bool
    season_number: int
    duration_ms: int
    is_premium_only: bool
    maturity_ratings: list[str]
    id: str
    seo_title: str
    season_display_number: str
    is_clip: bool
    season_id: str
    sequence_number: float
    availability_status: str
    slug: str
    season_title: str
    recent_audio_locale: str
    upload_date: AwareDatetime
    series_id: str
    seo_description: str
    closed_captions_available: bool
    next_episode_id: str | None = None
    is_mature: bool
    subtitle_locales: list[str]
    episode_air_date: AwareDatetime
    is_subbed: bool
    season_tags: list[str]
    next_episode_title: str | None = None
    premium_date: None
    availability_notes: str
    channel_id: str
    slug_title: str
    hd_flag: bool
    premium_available_date: AwareDatetime
    audio_locale: str
    availability_starts: AwareDatetime
    listing_id: str
    free_available_date: AwareDatetime
    description: str
    recent_variant: str
    season_sequence_number: int
    production_episode_id: str
    available_offline: bool
    roles: list[str]
    eligible_region: str
    identifier: str
    episode_number: int | None = None
    extended_maturity_rating: ExtendedMaturityRating
    series_slug_title: str
    season_slug_title: str
    episode: str
    images: Images
    ad_breaks: list[AdBreak] | None = None
    content_descriptors: list[str] | None = None
    streams_link: str | None = None


class Meta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    versions_considered: bool


class Episodes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    total: int
    data: list[Datum]
    meta: Meta
